from pathlib import Path

from docx import Document
from docx.enum.text import WD_BREAK
from docx.shared import Pt, RGBColor


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "EK_form_incl_checklist_2026_official.docx"
OUTPUT = ROOT / "01_ethics_application_OFFICIAL_FORM_DRAFT.docx"


def set_text(cell, text, *, size=9, red=False):
    cell.text = text
    for paragraph in cell.paragraphs:
        for run in paragraph.runs:
            run.font.name = "Arial"
            run.font.size = Pt(size)
            if red or "TO CONFIRM" in run.text:
                run.font.color.rgb = RGBColor(165, 35, 35)


def append_text(cell, text, *, size=9, bold=False, red=False):
    paragraph = cell.add_paragraph()
    run = paragraph.add_run(text)
    run.bold = bold
    run.font.name = "Arial"
    run.font.size = Pt(size)
    if red:
        run.font.color.rgb = RGBColor(165, 35, 35)


def mark_checklist(table, row_index, answer):
    yes = answer == "yes"
    set_text(table.rows[row_index].cells[1], f"{'☒' if yes else '☐'} Yes", size=9)
    set_text(table.rows[row_index].cells[2], f"{'☐' if yes else '☒'} No", size=9)


document = Document(SOURCE)

# Page 1: principal investigator and project summary.
principal = document.tables[0]
set_text(
    principal.cell(0, 1),
    "TO CONFIRM: Principal investigator",
    red=True,
)
set_text(principal.cell(1, 1), "Science and Technology for Peace and Security (PEASEC)")
set_text(principal.cell(2, 1), "Department of Computer Science, Technical University of Darmstadt")

project = document.tables[1]
set_text(project.cell(0, 1), "Local Trait Inference on Smartphones: User Perceptions of On-Device AI Profiling")
set_text(
    project.cell(1, 1),
    "This bachelor-thesis study examines how adults perceive privacy-relevant profiles generated by an AI model directly on their Android phone. Participants select approximately 20 of their own images or PDF documents. Raw files remain on the device; the app displays probabilistic file-level inferences and a combined profile. Participants complete privacy, technology-affinity, demographic, per-inference, and final questions. Optional front-camera tracking retains emotion labels but no images. Outcomes include expected capability, perceived accuracy, sensitivity, surprise, concern, and willingness to grant file access.",
    size=8,
)
set_text(project.cell(2, 1), "26 May 2026 to 30 November 2026")
set_text(project.cell(3, 1), "1 September 2026 to 31 October 2026 at the latest; only after a positive ethics vote")
set_text(
    project.cell(4, 1),
    "Atabey Tarik Akkum (student researcher); Simon Althaus, M.Sc. (thesis supervisor); Dr. rer. nat. Nina Gerber (role to confirm); TO CONFIRM: principal investigator and final data-access list",
    size=8,
)
set_text(
    project.cell(5, 1),
    "☒ B.A. Thesis     ☐ M.A. Thesis     ☐ Dissertation\n☐ Course     ☐ Research funded from own resources     ☐ Third-party funding     ☐ Other",
    size=8,
)
set_text(
    project.cell(6, 1),
    "☐ Journal requirement     ☐ Funding-body requirement\n☒ The project touches on ethically relevant issues: personal data, privacy-sensitive AI inferences, optional camera-based classification, and possible incidental third-party information.     ☐ Other",
    size=8,
)

# Page 2: checklist. Yes only for third-party impact and personal data.
checklist = document.tables[2]
for index in range(13):
    mark_checklist(checklist, index, "yes" if index in {6, 7} else "no")
mark_checklist(checklist, 14, "no")

# Page 3: detailed description in the official response areas.
details = document.tables[3]
set_text(
    details.cell(1, 0),
    "Aim and design. Modern smartphones can run multimodal AI locally and infer interests, activities, plans, educational or occupational context, and other personal signals without transmitting the underlying files. This within-participant app study examines what local AI can infer from participant-selected files; how unexpected, sensitive, and accurate participants perceive each inference; whether a combined profile changes expectations, privacy concern, reassurance about local processing, and willingness to grant broad file access; and how IUIPC-8 privacy concern and ATI technology affinity relate to these outcomes.\n\n"
    "Participants and recruitment. Approximately 100 adults aged 18 or older who can consent and use the Android prototype will participate. Minors, patients, and vulnerable groups are not specifically recruited. TO CONFIRM: recruitment route, remote or supervised setting, and compensation. Recruitment will avoid direct dependency relationships and coercion.\n\n"
    "Procedure. Participants read the information sheet and provide required in-app consent; optional front-camera tracking has a separate opt-in. They complete demographic items, IUIPC-8, ATI, and baseline local-AI questions. They then select approximately 20 of their own images or PDFs. They are instructed not to choose files depicting identifiable third parties or containing another person's personal information. Images are analyzed locally by Gemma 4 E2B; for PDFs, only a rendered first-page preview is analyzed. After each successful inference, participants rate unexpectedness, sensitivity, and perceived accuracy on five-point verbal scales. The app then generates one compact probabilistic profile, followed by six final questions concerning local AI capability, repeated background profiling, local-processing reassurance, summary transmission, commercial use, and future file access. One pseudonymized study record is exported. Raw files and camera images are excluded.\n\n"
    "Duration and burden. The active procedure is estimated at 25–40 minutes; first-time model download may add waiting time and will be piloted. Participation may be stopped at any time without disadvantage. No physical risks are expected. Inferences may cause mild concern, surprise, embarrassment, or discomfort. Participants control file selection, may skip files, need not select highly sensitive files, and are told that outputs are uncertain guesses rather than facts or diagnoses. There is no guaranteed personal benefit. The study may improve understanding of privacy expectations and appropriate safeguards for on-device AI.",
    size=8,
)
set_text(
    details.cell(4, 0),
    "Personal data: Questionnaire answers, consent decisions, ratings, model-generated inferences, the combined profile, technical metadata, and optional derived emotion labels are processed under a random study ID. Data minimization, restricted access, purpose limitation, and agreed deletion periods apply. Raw selected files remain local and are not exported.\n\n"
    "Potentially affected third parties: A selected file could contain another person's image or information. Participants are explicitly instructed not to select such files unless that person has independently consented. Files can be removed, no raw file is exported, and the final implementation replaces filenames and local URIs with random per-file identifiers.\n\n"
    "Ethical sensitivity: The study makes privacy consequences visible but uses no deception or coercion. Outputs are labelled probabilistic. Participants may stop immediately. Optional camera tracking is separately consented to, does not identify or diagnose participants, and retains only timestamps, event labels, predicted emotion labels, confidence values, and model metadata. Temporary image files will be deleted immediately after classification.",
    size=8,
)
set_text(
    details.cell(7, 0),
    "The study follows the EU General Data Protection Regulation (GDPR), the Hessian Data Protection and Freedom of Information Act (HDSIG), informed-consent, data-minimization and purpose-limitation principles, the DFG Guidelines for Safeguarding Good Research Practice, and applicable TU Darmstadt research-data and information-security requirements. Data collection starts only after a positive ethics vote and alignment of the app, participant information, questionnaires, and actual data flow. The final server, retention, access, and distribution arrangement will be approved by the principal investigator and reviewed with the TU Darmstadt Data Protection Officer if required.",
    size=8,
)

# Page 4: data-protection questions and exact answer rows.
protection = document.tables[4]
answers = {
    2: "App-based experiment and questionnaires using an Android prototype: in-app consent; demographic items; IUIPC-8; ATI; baseline, per-inference and final ratings; local Gemma inference; technical runtime metadata; and optional local front-camera emotion classification.",
    4: "Approximately 100 adults aged 18 or older. Minors, patients, and vulnerable groups are not targeted. Third parties are potentially affected only if a participant disregards the instruction not to select files containing other identifiable people or their data.",
    6: "Before collection, participants receive the full information sheet and confirm initially unticked required consent statements. They consent to participation, local processing of deliberately selected files, and pseudonymized export of questionnaire and inference data. Camera tracking requires a separate optional opt-in. Withdrawal is possible without disadvantage.",
    8: "Random study ID; age group, gender and education category; IUIPC-8 and ATI responses; local-AI expectation items; consent decisions; per-inference unexpectedness, sensitivity and perceived-accuracy ratings; model-generated inferences and combined profile; model/runtime metadata, latency and timestamps; optional derived emotion label and confidence. No raw files, camera frames, original filenames, local paths, names, email addresses, or phone numbers are included in the final export.",
    10: "a) Raw selected files are not copied to the research server; rendered previews and temporary camera frames are deleted immediately after use or at latest when the local session ends. b) TO CONFIRM: periods for pseudonymized working data and anonymized research data. c) TO CONFIRM: separate retention period for consent records. d) No audio is collected; temporary camera images are deleted immediately and only derived labels remain under the study ID.",
    12: "The app assigns a random study ID unrelated to identity and random per-file identifiers. Any recruitment contact details are stored separately and never joined to study records. Publications use aggregate anonymized results. Participants can use the study ID to request deletion until the confirmed anonymization cutoff.",
    14: "Raw-file and camera-frame analysis occurs locally. One pseudonymized JSON record is transmitted after consent over encrypted transport to TO CONFIRM: approved TU/PEASEC server and safeguards. Access is role-restricted and institutional backup/deletion procedures apply. Production model distribution must avoid undisclosed third-party IP-address transfer, for example through approved TU hosting or supervised preinstallation.",
    16: "Atabey Tarik Akkum and TO CONFIRM: final named principal investigator/supervisor access list. Access is restricted to the study team; researchers are bound by institutional confidentiality and data-protection obligations.",
    18: "Participants may request deletion using their study ID until TO CONFIRM: date or processing milestone at which records are irreversibly anonymized and can no longer be linked to one participation.",
    20: "No reuse or publication of raw participant files or camera images. Anonymized aggregate results may be used in the bachelor thesis and related scientific publications or presentations. TO CONFIRM: whether pseudonymized record-level data may be retained; recommended default is no reuse beyond this approved project without renewed review.",
}
for row_index, answer in answers.items():
    set_text(protection.rows[row_index].cells[0], answer, size=8, red="TO CONFIRM" in answer)

# Page 5: attachments. Keep the signature area blank for the final principal investigator.
set_text(protection.rows[22].cells[0], "☒ Declaration of consent", size=9)
set_text(protection.rows[23].cells[0], "☒ Questionnaire(s)", size=9)
set_text(protection.rows[24].cells[0], "☐ Research proposal", size=9)
set_text(protection.rows[25].cells[0], "☐ Images", size=9)
set_text(protection.rows[26].cells[0], "☐ other:", size=9)
append_text(
    protection.rows[28].cells[0],
    "TO CONFIRM: Principal investigator must review, date, and sign before submission.",
    size=8,
    red=True,
)

document.save(OUTPUT)
print(OUTPUT)
